name: Builds

on: [push, pull_request]

jobs:

  Windows:
    name: Windows latest
    runs-on: windows-latest 
    strategy:
      matrix:
        config: [RelWithDebInfo, Debug]

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup vs prompt
      uses: ilammy/msvc-dev-cmd@v1

    - name: Build
      run: |
        cd tests\build
        .\build.bat ${{ matrix.config }}

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: win64-${{ matrix.config }}
        path: |
          tests/build/tests.exe
          tests/build/tests.pdb

  Linux2004Gcc:
    name: Ubuntu 20.04
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        compiler:
          - cc: gcc-10
            cxx: g++-10
          - cc: clang-11
            cxx: clang++-11
        config: [RelWithDebInfo, Debug]

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Grab latest gcc
      run: |
        sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
        sudo apt-get -y update
        sudo apt install -y g++-10 ninja-build
        sudo bash -c "$(wget -O - https://apt.llvm.org/llvm.sh)"

    - name: Build
      run: |
        cd tests/build
        chmod u+x ./build.sh
        CC=${{ matrix.compiler.cc }} CXX=${{ matrix.compiler.cxx }} ./build.sh ${{ matrix.config }}

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: lin64-${{ matrix.compiler.cxx }}-${{ matrix.config }}
        path: |
          tests/build/tests
